spring:
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
    show-sql: true
  sql:
    init:
      mode: always
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://127.0.0.1:13306/researchdb
    username: research
    password: research

graphql:
  spqr:
    gui:
      enabled: true
